### ISSUE TITLE
Some additions.

### ISSUE THREAD

**Issue by Lalarian** [planeturban/15khz#7]
Hello!
I recently added some monitors I had for testing to the old list on wikidot.
Now I have seen, that your list seems to be the most recent incarnation.
Sadly all monitors had negatives results, but of course still would be useful for people to know.
Maybe you would like to add these monitors? 
:)
(I removed most Spaces for making it fit the width limit of the Github-Editor at FullH, you can find the matching column by counting the | (pipe) symbols.)

Make|Model|PanelType|Size(in. diag.)|x-Res|y-Res|AspectRatio(x:y)|VideoInputs| 15kHzRGBSupport|SyncOn Green|Comments

Eizo | FlexScan S1931 |   | 19 | 1280 | 1024 | 5:4 | DVI, VGA | No (at least not with PAL...)|"Out of specification 50Hz"|(specs)
Fujitsu | B22W-5 ECO |   | 22 | 1680 | 1050 | 16:0 | DVI, VGA | No |   | black screen
FujitsuSiemens|Scaleoview L19-2 L9ZA K1117-V173|TN|19|1280|1024|5:4|VGA|Not working ("invalid signal",black screen) |   | LG | D2542P-PN | TFT | 25 | 1920 | 1080 | 16:9 | VGA | "out of spec 15kHz/50Hz" |   | (specs)
LG | DM2780D | TFT | 27 | 1920 | 1080 | 16:9 | VGA | "15kHz/50Hz Invalid Format" |   | (specs)
Medion | MD 32117 PQ | TN | 17 | 1280 | 1024 | 5:4 | VGA | No | |"Mode not supported"
Samsung|Samsung XL2370 (EF23WS)|TFT|23|1920|1080|16:9| DVI, HDMI |No|   | ("15kHz/50Hz invalid signal")

And a new one that I didn't enter there, yet:
FujitsuSiemens|Scaleoview X20W-2 TFT20W90PS|TN|20|1680|1050|16:10|VGA| No | just black

**Comment by planeturban** [comment]
Half of the idea to move the list from forums and other places to a git repo is that anyone can fork, edit and do a pull request. So try to edit the readme yourself and keep the formatting. I'm rooting for you! :)

(I'll help if there's a problem. :) )

**Comment by Lalarian** [comment]
Yes, there is a problem - or even multiple problem? xD
1. How yo I know whether I should fork or open a pull request?
2. How could I edit the list?
3. I tried opening a pull request, but I couldn:
I clicked on "Pull requests", then on "New pull request" and then I get to a new site, with a greyed out button "Create pull request". I don't know that to do from there. I also had a look at the branches, but there was no other choice than the anyway selected default.

Thank you for helping! :)

**Comment by planeturban** [comment]
I think this is everything. I'll add another md-file with this info. 

1. Top right conrner, press “Fork”. Select a destination.
2. Open the newly forked repo and press the pencil in the top right corner of the readme.
3. Add your line(s), use “Preview changes” to make sure the table is generated ok. 
4. Scroll down. Add a description (optional, but sugested). 
5. Press “Commit changes”.
6. Press “Pull requests”, left corner. Select “New pull request.”
7. Press “Create pull request”.
8. Press “Create pull request”.

**Comment by Lalarian** [comment]
Thank you very much for the introduction!
Github now seems way less intuitive than I would have expected, but your precise instruction make up for this.
Anyway, I still have a problem editing the table. Everytime I add a line, when I try the Preview, I always get "Unable to load this preview, sorry."
I even tried copying one of the existing lines and just changing the contents, for having no illegal symbols or false formatting in there, but it still won't work :(
I also copy'n'pasted the whole table into Notepadqq locally and has it show all symbols- The added line is absolutely flawless.
Then I just duplicated an existing line and found, that even this makes rendering the table impossible.
Removing the added line (no matter if self edited or just duplicated original line) will make the table functional again.
Maybe it's a compatibility problem with my Waterfox browser or one of it's AddOns.
Edit:
Sigh! Tried it with Chrome and it doesn't work either :(
I got no idea what this could be..
I can edit the remaining txt no problem.
But as soon as I do the slightest change to the table, it becomes corrupted. Even just changing an existing letter to another one, or removing, or adding a letter in an already existing line, corrupts the table. In both web browsers.
Only remaining possible issue I can think of, would be Github having a temporary server problem right now, causing the table processing to fail... But of course this explanation would be too easy..

OK, another thing adding to confusion:
I now just created an own repository for testing, and edited the readme file - and it's working fine.
I can copy the whole table there, edit, add, remove and whatever without a problem. The preview will load successfully.

**Comment by planeturban** [comment]
Ah, easiet way that I've found is to set the editor to "No wrap", editor top corner. That way you'll see the cells as they should be. I'm guessing you didn't copy two lines (when in softwrap mode):

<img width="1275" alt="Screenshot 2020-12-06 at 11 40 05" src="https://user-images.githubusercontent.com/4372835/101277936-250c3800-37b8-11eb-8f88-f79b99ec810f.png">


No wrap:

<img width="1376" alt="Screenshot 2020-12-06 at 11 43 23" src="https://user-images.githubusercontent.com/4372835/101277961-4836e780-37b8-11eb-8e6d-644189b62ff7.png">
<img width="332" alt="Screenshot 2020-12-06 at 11 40 36" src="https://user-images.githubusercontent.com/4372835/101277963-4b31d800-37b8-11eb-916f-c949935f4f82.png">


I probably should remove all excess spaces.. I'll see what I can do to make it easier..

**Comment by Lalarian** [comment]
Yeah, I have it set to "No wrap" already.
As Github let me edit anything else, but not the existing table, I just tried a workaround and it worked:

1. I cut the whole table from the document and paste it locally.
2. I commit the document without the table at Github.
3. Edit the table locally.
4. Edit the document online and paste the edited table.
5. And voila: Preview and Commit are working.

But this procedure is terrible. And even after doing so once, Github still won't let me edit the existing table, but I would have to perform these steps everytime. :(

_Looks like Github had a bug to me, which simply would render a table corrupt after modification._

Regarding the spaces I wondered: Could we also use tabs instead? The spaces are a bit uncomfortable.
Edit:
OK! The easy workaround of course is to just commit, without using the preview. It simply works.

**Comment by Lalarian** [comment]
I now have added all displays subsequently and Opened a pull request.
Github tells me:

Add more commits by pushing to the master branch on Lalarian/15khz.
Review required
At least 1 approving review is required by reviewers with write access.
This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.
Conflicting files
README.md

Is this OK so far? :)

**Comment by planeturban** [comment]
Closing here.. Got them added in another PR.
